# Generated by Django 3.2 on 2021-11-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyinfo',
            options={},
        ),
    ]
